### ISSUE TITLE
2022 Critical Fixes Tracking

### ISSUE THREAD

**Issue by sadnow** [sadnow/360Diffusion#4]
### Critical tasks
- [x] Revise depcrecated real-esrgan param 'model_path' (Referenced in #3)
- [x] Update links if necessary - see [this](https://twitter.com/sadly_existent/status/1448598872054329352) for reference
- [ ] Revise project to point to direct to self-forked repos (longevity)

**Comment by sadnow** [comment]
Majority resolved with a878e68afad1382ddd0c2599d433b2467118da94
